--- #Change user passwords
- hosts: soullab
  become: yes
  tasks:
    - name: Change user password
      user:
        name: kubeman
        update_password: always
        password: "{{ newpassword | password_hash('sha512') }}"
